### ISSUE TITLE
reCaptcha only showing on Website Refresh

### ISSUE THREAD

**Issue by dbueno1988** [aryehraber/statamic-recaptcha#10]
I have an issue when I click on a menu on the website as this template don't make a refresh of the page and the Google reCaptcha only gets loaded if I refresh the page if I click on the menu it doesn't shows at all. 

How could I approach this situation?
Thanks for your help!

Diego.

**Comment by aryehraber** [comment]
You should be able to trigger the reCAPTCHA via JS in that case, have a look at the [reCAPTCHA docs](https://developers.google.com/recaptcha/docs/display#js_api) on how to render manually.

I won't be able to provide further support but here's a snippet from a project I had to do a similar thing:

```html
<div class="recaptcha"></div>

<script>
const recaptcha = document.querySelector('.recaptcha')

if (recaptcha) {
  axios.get('/!/Recaptcha/siteKey').then(resp => {
    window.grecaptcha.render(recaptcha, { sitekey: resp.data })
  })
}
</script>
```

The endpoint `/!/Recaptcha/siteKey` is made available via this Addon and should return the configured `site_key`.

Also note, before the above code runs, you'll also need to make sure `window.grecaptcha` is available/ready.

Good luck!

**Comment by cibgraphics** [comment]
Maybe I misunderstanding something. To render the captcha, I need to do an explicit render which I can do just fine. I can get a response via javascript which gives me a token. But without the use of the plugin (because I am using explicit rendering), I can no longer use the plugin to actually send it to Google for verification. 

Am I missing something?
