### ISSUE TITLE
Recaptcha failed

### ISSUE THREAD

**Issue by rolinbos** [aryehraber/statamic-recaptcha#12]
I want to have a invisible recaptcha check on my website.
I have added 
`
{{ recaptcha }}
{{ recaptcha:disclaimer }}
`
Inside my form and in the control panel I have added de site key and the secret key and set the invisible toggle to true. And the site keys I have set it the same way.

On the website I get this icon: 
![Schermafbeelding 2019-08-05 om 16 03 11](https://user-images.githubusercontent.com/34242298/62470358-8eca9b00-b79a-11e9-9acf-bcc2ae904c1a.png)

How can I solve this problem?

**Comment by Oleafeon** [comment]
Did you solve this?

**Comment by rolinbos** [comment]
@4kets No I haven't solved it.

**Comment by aryehraber** [comment]
Just retested this using latest version of the Addon on latest {{S}} and seems to be working fine. 

Did you add `{{ recaptcha:head }}` as per the [Usage Docs](https://github.com/aryehraber/statamic-recaptcha#usage)? This tag is important because 1) it adds the necessary JS to make the Recaptcha work, and 2) it adds some css if the `Hide reCAPTCHA Badge` toggle is on.

If it still doesn't work after checking these things, I'd advise you to have a closer look using Devtools Inspector to see why the css isn't taking effect — perhaps some of your own styles are overriding this setting.
