### ISSUE TITLE
How to access the error message directly.

### ISSUE THREAD

**Issue by Helen2hang** [aryehraber/statamic-recaptcha#14]
Hi,
 
May I know how I can get the error message of the recaptcha directly? I can get it from `{{form:errors}}` but this gives me all the other errors in the forms as well. However, I only want the error message of the recaptcha.

Please and thanks!

**Comment by aryehraber** [comment]
@Helen2hang Thanks for bringing up this issue, you're the first to ask for this feature! 

Turns out it isn't currently possible, but I already found a solution so hope to push a minor update soon giving you access to `{{ error:recaptcha }}` which will output the error message.

Will tag this issue once it's released so you're updated!

**Comment by Helen2hang** [comment]
Thank you!!
