### ISSUE TITLE
Invisible success message response missing

### ISSUE THREAD

**Issue by admench** [aryehraber/statamic-recaptcha#6]
When setting up with a non-invisible set of keys and ensuring the plugin has been set to non-invisible, the form submits and notifies the user that it was succcesful.

By changing the api keys to the ones for an invisible setup, and checking the plugin setting is for invisible the form submits but no success message is returned to the user, the form fields just stay populated.

**Comment by aryehraber** [comment]
The addon doesn't return any data/messages on success, only on error, so I'm not really sure what's going on in this case.

**Comment by aryehraber** [comment]
I'm closing this issue because it has been inactive for some time. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://statamic.com/marketplace/addons/google-recaptcha). You can also contribute directly by providing a PR.

Thank you!
