### ISSUE TITLE
Can Recaptcha be used on user registration?

### ISSUE THREAD

**Issue by danielfowler** [aryehraber/statamic-recaptcha#7]
I'm going through implementation and where I'm supposed to select which forms will use Recaptcha, there's no option to put it on User Registration, presumably because I don't have a formset for that.

Is user registration not supported, or is there some way I can still implement?

**Comment by aryehraber** [comment]
Hey @danielfowler, sorry for the delayed reply... 

You're correct, this addon currently only supports Formsets. You're the first to point out this issue/missing feature, but definitely a good FR! 

If you are able, feel free to submit a PR to add this feature, otherwise it'll have to wait until I have some spare time or need the feature myself. Thanks!
